server:
  port: 9080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: user123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
